import type { Metadata } from 'next'
import { Geist, Geist_Mono, Inter, Playwrite_NO } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import LanguageSwitcher from './components/ui/LanguageSwitcher'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin']
})

const Play_write = Playwrite_NO({
  variable: '--font-play_n' // Define a CSS variable
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} ${Play_write.variable} antialiased h-screen flex flex-col`}
      >
        <header className='bg-stone-200 p-8'>
          <nav className='container flex justify-between'>
            <ul className='flex gap-4'>
              <li>
                <Link
                  href='/'
                  className='text-sm font-medium uppercase text-stone-400'
                >
                  Home
                </Link>
              </li>
              <li>
                <Link
                  href='/posts'
                  className='text-sm font-medium uppercase text-stone-400'
                >
                  Old Posts
                </Link>
              </li>
              <li>
                <Link
                  href='/af/blogs-page'
                  className='text-sm font-medium uppercase text-stone-400'
                >
                  Blogs
                </Link>
              </li>
              <li>
                <Link
                  href='/af/the-global-bar-page'
                  className='text-sm font-medium uppercase text-stone-400'
                >
                  The Global Bar
                </Link>
              </li>
            </ul>
            <LanguageSwitcher />
          </nav>
        </header>

        <main>{children}</main>

        {/* <footer className='bg-stone-200 text-sm font-medium uppercase text-stone-400 px-8 py-4'>
          <div className='container'>
            <p>Footer</p>
          </div>
        </footer> */}
      </body>
    </html>
  )
}
